name: Setup SSH Server on GitHub Runner

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  setup-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -b 4096 -C "github-actions" -f server-key -N ""
          mkdir -p ~/.ssh
          cat server-key.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          echo "SSH Key generated & added to authorized_keys"

      - name: Install & Start SSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          sudo ufw allow 22
          echo "SSH Server installed & started"

      - name: Get Public IP
        run: |
          PUBLIC_IP=$(curl -s http://checkip.amazonaws.com)
          echo "Connect using: ssh -i server-key runner@${PUBLIC_IP}"
          echo "PUBLIC_IP=${PUBLIC_IP}" >> $GITHUB_ENV

      - name: Keep Runner Alive (Prevent Auto-Exit)
        run: |
          echo "SSH Server is running! Use the command above to connect."
          sleep 1h  # Keeps the runner alive for 1 hour

